using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyCode;

namespace MyCode.Tests
{
    [TestClass]
    public class Class1Tests
    {
        [TestMethod]
        public void Test_Class1_FirstMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class1_SecondMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class1_ThirdMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class1_ThirdMethod2_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}